// <auto-generated />
using System;
using AnniversaryWebProduct.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnniversaryWebProduct.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625231026_RemovedVirtualHistory")]
    partial class RemovedVirtualHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnniversaryWebProduct.Models.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChatId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ChatId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.HistoryInstance", b =>
                {
                    b.Property<int>("HistoryInstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryInstanceId"));

                    b.Property<DateOnly>("HistoryDate")
                        .HasColumnType("date");

                    b.HasKey("HistoryInstanceId");

                    b.ToTable("HistoryInstance");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.MemoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HistoryInstanceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("VideoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.HasIndex("HistoryInstanceId");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("VideoId")
                        .IsUnique();

                    b.ToTable("MemoryItem");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TimerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Timer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2025, 6, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            DateStart = new DateTime(2025, 6, 25, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            TimerName = "Anniversary Date"
                        });
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Video", b =>
                {
                    b.Property<int>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VideoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DurationInSeconds")
                        .HasColumnType("numeric");

                    b.Property<string>("FileDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.MemoryItem", b =>
                {
                    b.HasOne("AnniversaryWebProduct.Models.Chat", "Chat")
                        .WithOne("MemoryItem")
                        .HasForeignKey("AnniversaryWebProduct.Models.MemoryItem", "ChatId");

                    b.HasOne("AnniversaryWebProduct.Models.HistoryInstance", "HistoryInstance")
                        .WithMany("MemoryItems")
                        .HasForeignKey("HistoryInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnniversaryWebProduct.Models.Image", "Image")
                        .WithOne("MemoryItem")
                        .HasForeignKey("AnniversaryWebProduct.Models.MemoryItem", "ImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnniversaryWebProduct.Models.Video", "Video")
                        .WithOne("MemoryItem")
                        .HasForeignKey("AnniversaryWebProduct.Models.MemoryItem", "VideoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Chat");

                    b.Navigation("HistoryInstance");

                    b.Navigation("Image");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Chat", b =>
                {
                    b.Navigation("MemoryItem")
                        .IsRequired();
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.HistoryInstance", b =>
                {
                    b.Navigation("MemoryItems");
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Image", b =>
                {
                    b.Navigation("MemoryItem")
                        .IsRequired();
                });

            modelBuilder.Entity("AnniversaryWebProduct.Models.Video", b =>
                {
                    b.Navigation("MemoryItem")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
